[profile.default]
src = "contracts/src"
out = "output"
test = "contracts/test"
script = "contracts/script"
libs = ["contracts/lib"]
solc_version = "0.8.19"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
